# Model
model = "gpt-5-codex"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"

# Sandbox

sandbox_mode = "workspace-write" # Make cwd writable

[sandbox_workspace_write]
network_access = true # Allow network access

[shell_environment_policy]
# NOTE: Codex doesn't support variable expansion in the config file yet: https://github.com/openai/codex/issues/2680
set = { AGENT = "true", GIT_CONFIG_GLOBAL = "${HOME}/.config/git/agent.config" } # Use agent git config

# Tools

[tools]
web_search = true # Allow to google things
